name: Export Draw.io → PDF
on:
  push:
    paths:
      - '**/*.drawio'
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Export drawio → PDF
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: '.'
          format: pdf
          output: 'export/pdf'
          remove-page-suffix: false
          crop: true
          embed-diagram: true
      - name: Commit cambios
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: PDF‑Export synchronisiert'
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
