name: Export Draw.io → PDF
on:
  push:
    paths:
      - '**/*.drawio'
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script to split Draw.io layers
        run: |
          FILE=$(find . -name '*.drawio' | head -n 1)
          python split.py --input_file "$FILE" --output_dir testdir
      
      - name: Export drawio → PDF
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: 'output_layers/*'
          format: pdf
          output: 'export/pdf'
          remove-page-suffix: false
          crop: true
          embed-diagram: true
      - name: Commit cambios
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: PDF‑Export synchronisiert'
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
