name: Export Draw.io Diagrams

on:
  push:
    paths:
      - '*.drawio'

jobs:
  export-drawio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies and Draw.io
      run: |
        sudo apt-get update && sudo apt-get install -y xvfb libxml2-utils
        wget https://github.com/jgraph/drawio-desktop/releases/download/v26.2.2/drawio-x86_64-26.2.2.AppImage -O drawio
        chmod +x drawio
        ./drawio --appimage-extract
        mkdir -p docs/images/

    - name: Count Pages in Draw.io File
      id: count
      run: |
        FILE=$(find . -name '*.drawio' | head -n 1)
        page_count=$(xmllint --xpath "count(//diagram)" "$FILE")
        echo "count=$page_count" >> $GITHUB_OUTPUT

    - name: Export PNG Images from Draw.io
      run: |
        FILE=$(find . -name '*.drawio' | head -n 1)
        OUT_DIR=diagrams
        PAGE_INDEX=0
        mkdir -p "$OUT_DIR"
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99
        sleep 3
        echo "Using file: $FILE"
        for LAYER in "${LAYERS[@]}"; do
            echo "Exporting layer: $LAYER"
            ./squashfs-root/drawio -x -f pdf --page-index "$PAGE_INDEX" -o "$OUT_DIR/${LAYER}.pdf" "$FILE"
        done

    - name: Commit and Push Exported Images
      env:
        GITHUB_TOKEN: $
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add docs/images/
        git commit -m "Exported Draw.io diagrams [skip ci]" || echo "No changes to commit"
        git push
