name: Export Draw.io Layers to PDFs and Commit

on:
  push:
    paths:
      - '*.drawio'

jobs:
  export-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install dependencies (AppImage)
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet
          sudo apt-get install -y xvfb
          
      - name: Install draw.io without FUSE
        run: |
          wget https://github.com/jgraph/drawio-desktop/releases/download/v28.0.6/drawio-x86_64-28.0.6.AppImage -O drawio.AppImage
          chmod +x drawio.AppImage
          ./drawio.AppImage --appimage-extract
          ln -s squashfs-root/drawio drawio
          
      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          
      - name: Export PDFs from layers
        run: |
          set -e
          FILE=$(find . -name '*.drawio' | head -n 1)
          OUT_DIR=diagrams
          PAGE_INDEX=0
          mkdir -p "$OUT_DIR"

          echo "Using file: $FILE"

          mapfile -t LAYERS < <(xmlstarlet sel -t -m "//object[@style='layer']" -v "@label" -n "$FILE")
          echo "Found layers: ${LAYERS[*]}"

          for LAYER in "${LAYERS[@]}"; do
            echo "Exporting layer: $LAYER"
            DISPLAY=:99  ./drawio \
              --no-sandbox \
              --export "$FILE" \
              --output "$OUT_DIR/${LAYER}.pdf" \
              --format pdf \
              --page-index "$PAGE_INDEX" \
              --layers "$LAYER" \
              --crop
          done

      - name: Check generated PDFs
        run: ls -l diagrams/

      - name: Commit and push PDFs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add diagrams/
          git commit -m "Update PDFs from Draw.io layers" || echo "No changes"
          git push
