name: Export Draw.io Layers to PDFs and Commit

on:
  push:
    paths:
      - '*.drawio'

jobs:
  export-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet xvfb libgtk-3-0 libxss1 libasound2t64

      - name: Download and extract Draw.io AppImage
        run: |
          wget https://github.com/jgraph/drawio-desktop/releases/download/v28.0.6/drawio-x86_64-28.0.6.AppImage -O drawio.AppImage
          chmod +x drawio.AppImage
          ./drawio.AppImage --appimage-extract
          ln -s squashfs-root/drawio drawio

      - name: Export PDFs from layers
        run: |
          set -e
          
          # We define the drawio application path first
          DRAWIO_APP="$GITHUB_WORKSPACE/squashfs-root/drawio"
          
          # Change directory to the drawio app's location to satisfy its sandbox
          cd "$GITHUB_WORKSPACE/squashfs-root"
          
          FILE_PATH="$GITHUB_WORKSPACE/$(find . -name '*.drawio' | head -n 1)"
          OUT_DIR="$GITHUB_WORKSPACE/diagrams"
          PAGE_INDEX=0
          
          # Create output directory in the main workspace
          mkdir -p "$OUT_DIR"
          
          echo "Using file: $FILE_PATH"
          test -f "$FILE_PATH" || (echo "File not found: $FILE_PATH" && exit 1)
          
          # xmlstarlet needs the full path to the file
          mapfile -t LAYERS < <(xmlstarlet sel -t -m "//object[@style='layer']" -v "@label" -n "$FILE_PATH")
          echo "Found layers: ${LAYERS[*]}"
          
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          export DISPLAY=:99
          
          for LAYER in "${LAYERS[@]}"; do
            echo "Exporting layer: $LAYER"
            # Now call the app from its directory, using absolute paths for files
            "$DRAWIO_APP" \
              --no-sandbox \
              --disable-gpu \
              --export "$FILE_PATH" \
              --output "$OUT_DIR/${LAYER}.pdf" \
              --format pdf \
              --page-index "$PAGE_INDEX" \
              --layers "$LAYER" \
              --crop
          done


      - name: Check generated PDFs
        run: ls -l diagrams/

      - name: Commit and push PDFs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add diagrams/
          git commit -m "Update PDFs from Draw.io layers" || echo "No changes"
          git push
