name: Export Draw.io Diagrams via CLI

on:
  push:
    paths:
      - '*.drawio'

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install cli-diagram
        run: npm install -g @hediet/cli-diagram

      - name: Export each layer
        run: |
          FILE=$(find . -name '*.drawio' | head -n 1)
          OUT_DIR=diagrams
          mkdir -p "$OUT_DIR"

          mapfile -t LAYERS < <(xmlstarlet sel -t -m "//object[@style='layer']" -v "@label" -n "$FILE")

          for LAYER in "${LAYERS[@]}"; do
            echo "Exporting $LAYER"
            cli-diagram export \
              --input "$FILE" \
              --output "$OUT_DIR/${LAYER}.pdf" \
              --page 0 \
              --layer "$LAYER" \
              --format pdf
          done

      - name: Commit and push PDFs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add diagrams/
          git commit -m "Export PDFs from Draw.io layers" || echo "No changes"
          git push
